/**
 * Generated by Apache Flex Cross-Compiler from org/apache/flex/core/DropType.as
 * org.apache.flex.core.DropType
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('org.apache.flex.core.DropType');



/**
 * @constructor
 */
org.apache.flex.core.DropType = function() {
};


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.flex.core.DropType.MOVE = "move";


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.flex.core.DropType.COPY = "copy";


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.flex.core.DropType.CANCEL = "cancel";


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.flex.core.DropType.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'DropType', qName: 'org.apache.flex.core.DropType'}] };
