/**
 * Generated by Apache Flex Cross-Compiler from org/apache/flex/core/SimpleCSSStyles.as
 * org.apache.flex.core.SimpleCSSStyles
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('org.apache.flex.core.SimpleCSSStyles');



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion FlexJS 0.0
 * @constructor
 */
org.apache.flex.core.SimpleCSSStyles = function() {
  
  this.styleList = {"top":1, "bottom":1, "left":1, "right":1, "padding":1, "paddingLeft":1, "paddingRight":1, "paddingTop":1, "paddingBottom":1, "margin":1, "marginLeft":1, "marginRight":1, "marginTop":1, "marginBottom":1, "verticalAlign":1, "fontFamily":1, "fontSize":1, "color":1, "fontWeight":1, "fontStyle":1, "backgroundAlpha":1, "backgroundColor":1, "backgroundImage":1, "borderColor":1, "borderStyle":1, "borderRadius":1, "borderWidth":1};
  ;
};


/**
 * @export
 * @type {Object}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.styleList;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.top;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.bottom;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.left;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.right;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.padding;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.paddingLeft;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.paddingRight;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.paddingTop;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.paddingBottom;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.margin;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.marginLeft;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.marginRight;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.marginTop;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.marginBottom;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.verticalAlign;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.fontFamily;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.fontSize;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.color;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.fontWeight;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.fontStyle;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.backgroundAlpha;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.backgroundColor;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.backgroundImage;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.borderColor;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.borderStyle;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.borderRadius;


/**
 * @export
 * @type {*}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.borderWidth;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.flex.core.SimpleCSSStyles.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'SimpleCSSStyles', qName: 'org.apache.flex.core.SimpleCSSStyles'}] };
