/**
 * Generated by Apache Flex Cross-Compiler from productsView\ProductListItem.mxml
 * productsView.ProductListItem
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes}
 */

goog.provide('productsView.ProductListItem');

goog.require('org.apache.flex.html.Container');
goog.require('org.apache.flex.html.ImageButton');
goog.require('org.apache.flex.html.accessories.NumericOnlyTextInputBead');
goog.require('samples.flexstore.ProductListEvent');




/**
 * @constructor
 * @extends {org.apache.flex.html.Container}
 */
productsView.ProductListItem = function() {
  productsView.ProductListItem.base(this, 'constructor');
  
  this.uid = (productsView.ProductListItem.idCounter++).toString();
  /**
   * @private
   * @type {org.apache.flex.html.accessories.CurrencyFormatter}
   */
  this.cf_;
  
  /**
   * @private
   * @type {org.apache.flex.binding.ContainerDataBinding}
   */
  this.$ID0_;
  
  /**
   * @private
   * @type {org.apache.flex.html.ImageButton}
   */
  this.removeButton_;
  
  /**
   * @private
   * @type {org.apache.flex.html.accessories.ToolTipBead}
   */
  this.$ID1_;
  
  /**
   * @private
   * @type {org.apache.flex.html.Image}
   */
  this.productImage_;
  
  /**
   * @private
   * @type {org.apache.flex.html.Label}
   */
  this.productName_;
  
  /**
   * @private
   * @type {org.apache.flex.html.Label}
   */
  this.productPrice_;
  
  /**
   * @private
   * @type {org.apache.flex.states.State}
   */
  this.$ID3_;
  
  /**
   * @private
   * @type {org.apache.flex.states.State}
   */
  this.$ID4_;
  
  /**
   * @private
   * @type {org.apache.flex.html.TextInput}
   */
  this.qty_;
  
  /**
   * @private
   * @type {org.apache.flex.html.accessories.NumericOnlyTextInputBead}
   */
  this.$ID2_;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldd;
  /**
   * @export
   * @type {Array}
   */
  this.mxmlsd = [
  [org.apache.flex.html.TextInput, 5, 'id', true, 'qty', 'width', true, 25, 'y', true, 3, 'style', true, 'textAlign:right;right:0;marginTop:0', 'beads', null, [org.apache.flex.html.accessories.NumericOnlyTextInputBead, 2, '_id', true, '$ID2', 'maxChars', true, 3, 0, 0, null], 0, 1, 'change', this.$EH1, null],
null];
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldp;

  this.generateMXMLAttributes
  ([3,
'className',
true,
'listItem',
'states',
null, [org.apache.flex.states.State, 3, '_id', true, '$ID3', 'name', true, 'compare', 'overrides', null, [], 0, 0, null, org.apache.flex.states.State, 3, '_id', true, '$ID4', 'name', true, 'showQuantity', 'overrides', null, [org.apache.flex.states.AddItems, 3, 'itemsDescriptorIndex', true, 0, 'position', true, 'after', 'relativeTo', true, 'productPrice', 0, 0, null, org.apache.flex.states.SetProperty, 3, 'target', true, 'productPrice', 'name', true, 'style', 'value', true, 'textAlign:right;right:25', 0, 0, null], 0, 0, null],
'beads',
null, [org.apache.flex.binding.ContainerDataBinding, 1, '_id', true, '$ID0', 0, 0, null],
0,
0
  ]);
  
};
goog.inherits(productsView.ProductListItem, org.apache.flex.html.Container);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
productsView.ProductListItem.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ProductListItem', qName: 'productsView.ProductListItem' }] };


/**
 * @private
 * @type {number}
 */
productsView.ProductListItem.idCounter = 0;


/**
 * @export
 * @type {string}
 */
productsView.ProductListItem.prototype.uid;


/**
 * @export
 * @const
 * @type {number}
 */
productsView.ProductListItem.HEIGHT = 30;


;


;


/**
 * @private
 * @type {Object}
 */
productsView.ProductListItem.prototype._data;


;


;


/**
 * @private
 * @type {Object}
 */
productsView.ProductListItem.prototype._itemRendererParent;


;


;


/**
 * @private
 */
productsView.ProductListItem.prototype.qtyChange = function() {
  this.product.qty = org.apache.flex.utils.Language._int(this.qty.text);
  var /** @type {samples.flexstore.ProductListEvent} */ event = new samples.flexstore.ProductListEvent(samples.flexstore.ProductListEvent.PRODUCT_QTY_CHANGE);
  event.product = this.product;
  this.dispatchEvent(event);
};


/**
 * @private
 */
productsView.ProductListItem.prototype.removeItem = function() {
  var /** @type {samples.flexstore.ProductListEvent} */ event = new samples.flexstore.ProductListEvent(samples.flexstore.ProductListEvent.REMOVE_PRODUCT);
  event.product = this.product;
  this.dispatchEvent(event);
};





Object.defineProperties(productsView.ProductListItem.prototype, /** @lends {productsView.ProductListItem.prototype} */ {
/** @export */
product: {
get: /** @this {productsView.ProductListItem} */ function() {
  return org.apache.flex.utils.Language.as(this._data, samples.flexstore.Product);
},
set: /** @this {productsView.ProductListItem} */ function(value) {
  this._data = value;
}},
/** @export */
data: {
get: /** @this {productsView.ProductListItem} */ function() {
  return this._data;
},
set: /** @this {productsView.ProductListItem} */ function(value) {
  this._data = value;
}},
/** @export */
itemRendererParent: {
get: /** @this {productsView.ProductListItem} */ function() {
  return this._itemRendererParent;
},
set: /** @this {productsView.ProductListItem} */ function(value) {
  this._itemRendererParent = value;
}}}
);/**
 * @export
 * @param {org.apache.flex.events.Event} event
 */
productsView.ProductListItem.prototype.$EH0 = function(event)
{
  this.removeItem();
};


/**
 * @export
 * @param {org.apache.flex.events.Event} event
 */
productsView.ProductListItem.prototype.$EH1 = function(event)
{
  this.qtyChange();
};


Object.defineProperties(productsView.ProductListItem.prototype, /** @lends {productsView.ProductListItem.prototype} */ {
/** @export */
    cf: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.cf_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.cf_) {
        this.cf_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'cf', null, value));
      }
    }
  },
  /** @export */
    removeButton: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.removeButton_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.removeButton_) {
        this.removeButton_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'removeButton', null, value));
      }
    }
  },
  /** @export */
    productImage: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.productImage_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.productImage_) {
        this.productImage_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'productImage', null, value));
      }
    }
  },
  /** @export */
    productName: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.productName_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.productName_) {
        this.productName_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'productName', null, value));
      }
    }
  },
  /** @export */
    productPrice: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.productPrice_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.productPrice_) {
        this.productPrice_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'productPrice', null, value));
      }
    }
  },
  /** @export */
    qty: {
    /** @this {productsView.ProductListItem} */
    get: function() {
      return this.qty_;
    },
    /** @this {productsView.ProductListItem} */
    set: function(value) {
      if (value != this.qty_) {
        this.qty_ = value;
        this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(this, 'qty', null, value));
      }
    }
  },
  'MXMLDescriptor': {
    /** @this {productsView.ProductListItem} */
    get: function() {
      {
        if (this.mxmldd == undefined)
        {
          /** @type {Array} */
          var arr = org.apache.flex.utils.Language.superGetter(productsView.ProductListItem,this, 'MXMLDescriptor');
          /** @type {Array} */
          var data = [
      org.apache.flex.html.accessories.CurrencyFormatter,
3,
'id',
true,
'cf',
'currencySymbol',
true,
'$',
'fractionalDigits',
true,
2,
0,
0,
null,
org.apache.flex.html.ImageButton,
6,
'id',
true,
'removeButton',
'backgroundImage',
true,
'assets/trashcan.png',
'width',
true,
14,
'height',
true,
14,
'y',
true,
5,
'beads',
null, [org.apache.flex.html.accessories.ToolTipBead, 2, '_id', true, '$ID1', 'toolTip', true, 'Remove from cart', 0, 0, null],
0,
1,
'click',
this.$EH0,
null,
org.apache.flex.html.Image,
5,
'id',
true,
'productImage',
'x',
true,
16,
'y',
true,
6,
'width',
true,
12,
'height',
true,
12,
0,
0,
null,
org.apache.flex.html.Label,
4,
'id',
true,
'productName',
'x',
true,
30,
'width',
true,
100,
'y',
true,
4,
0,
0,
null,
org.apache.flex.html.Label,
4,
'id',
true,
'productPrice',
'width',
true,
60,
'y',
true,
4,
'style',
true,
'textAlign:right;right:0',
0,
0,
null
      ];
        
          if (arr)
            this.mxmldd = arr.concat(data);
          else
            this.mxmldd = data;
        }
        return this.mxmldd;
      }
      }
    }
  });
  /**
   * @export
   */
  productsView.ProductListItem.prototype._bindings = [
  5,
  ["product", "qty"],
  null,
  ["qty", "text"],
  "HEIGHT",
  null,
  ["this", "height"],
  ["product", "image"],
  null,
  ["productImage", "source"],
  ["product", "name"],
  null,
  ["productName", "text"],
  function() { return this.cf.format(this.product.price); },
  null,
  ["productPrice", "text"],
  0,
  2,
  "product",
  "__NoChangeEvent__",
  [0,2,3,4],
  null,
  [
  1,
  2,
  "qty",
  "valueChange",
  0,
  null,
  null,
  2,
  2,
  "image",
  "valueChange",
  2,
  null,
  null,
  3,
  2,
  "name",
  "valueChange",
  3,
  null,
  null,
  4,
  2,
  "price",
  "valueChange",
  4,
  null,
  null,
  null],
  5,
  2,
  "cf",
  "valueChange",
  4,
  null,
  null,
  null];
  
