/**
 * Generated by Apache Flex Cross-Compiler from samples\flexstore\Product.as
 * samples.flexstore.Product
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes}
 */

goog.provide('samples.flexstore.Product');

goog.require('org.apache.flex.events.EventDispatcher');



/**
 * @constructor
 * @extends {org.apache.flex.events.EventDispatcher}
 */
samples.flexstore.Product = function() {
  samples.flexstore.Product.base(this, 'constructor');
};
goog.inherits(samples.flexstore.Product, org.apache.flex.events.EventDispatcher);


/**
 * @export
 * @type {number}
 */
samples.flexstore.Product.prototype.productId_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.name_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.description_;


/**
 * @export
 * @type {number}
 */
samples.flexstore.Product.prototype.price_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.image_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.experience_;


/**
 * @export
 * @type {boolean}
 */
samples.flexstore.Product.prototype.blazeds_;


/**
 * @export
 * @type {boolean}
 */
samples.flexstore.Product.prototype.mobile_;


/**
 * @export
 * @type {boolean}
 */
samples.flexstore.Product.prototype.video_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.highlight1_;


/**
 * @export
 * @type {string}
 */
samples.flexstore.Product.prototype.highlight2_;


/**
 * @export
 * @type {number}
 */
samples.flexstore.Product.prototype.qty_;


/**
 * @export
 * @param {Object} obj
 */
samples.flexstore.Product.prototype.fill = function(obj) {
  for (var /** @type {string} */ i in obj) {
    this[i] = obj[i];
  }
};Object.defineProperties(samples.flexstore.Product.prototype, /** @lends {samples.flexstore.Product.prototype} */ {
/** @export */
productId: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.productId_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.productId_) {
    var oldValue = this.productId_;
    this.productId_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "productId", oldValue, value));
}
}},/** @export */
name: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.name_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.name_) {
    var oldValue = this.name_;
    this.name_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "name", oldValue, value));
}
}},/** @export */
description: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.description_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.description_) {
    var oldValue = this.description_;
    this.description_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "description", oldValue, value));
}
}},/** @export */
price: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.price_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.price_) {
    var oldValue = this.price_;
    this.price_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "price", oldValue, value));
}
}},/** @export */
image: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.image_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.image_) {
    var oldValue = this.image_;
    this.image_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "image", oldValue, value));
}
}},/** @export */
experience: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.experience_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.experience_) {
    var oldValue = this.experience_;
    this.experience_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "experience", oldValue, value));
}
}},/** @export */
blazeds: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.blazeds_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.blazeds_) {
    var oldValue = this.blazeds_;
    this.blazeds_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "blazeds", oldValue, value));
}
}},/** @export */
mobile: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.mobile_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.mobile_) {
    var oldValue = this.mobile_;
    this.mobile_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "mobile", oldValue, value));
}
}},/** @export */
video: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.video_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.video_) {
    var oldValue = this.video_;
    this.video_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "video", oldValue, value));
}
}},/** @export */
highlight1: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.highlight1_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.highlight1_) {
    var oldValue = this.highlight1_;
    this.highlight1_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "highlight1", oldValue, value));
}
}},/** @export */
highlight2: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.highlight2_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.highlight2_) {
    var oldValue = this.highlight2_;
    this.highlight2_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "highlight2", oldValue, value));
}
}},/** @export */
qty: {
/** @this {samples.flexstore.Product} */
  get: function() {
  return this.qty_;
  },

/** @this {samples.flexstore.Product} */
set: function(value) {
if (value != this.qty_) {
    var oldValue = this.qty_;
    this.qty_ = value;
    this.dispatchEvent(org.apache.flex.events.ValueChangeEvent.createUpdateEvent(
         this, "qty", oldValue, value));
}
}}}
);


Object.defineProperties(samples.flexstore.Product.prototype, /** @lends {samples.flexstore.Product.prototype} */ {
/** @export */
featureString: {
get: /** @this {samples.flexstore.Product} */ function() {
  var /** @type {string} */ str = "";
  if (this.blazeds)
    str += "BlazeDS";
  if (this.mobile) {
    if (str.length > 0)
      str += "\n";
    str += "Mobile";
  }
  if (this.video) {
    if (str.length > 0)
      str += "\n";
    str += "Video";
  }
  return str;
}}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
samples.flexstore.Product.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Product', qName: 'samples.flexstore.Product'}] };
