/**
 * Generated by Apache Flex Cross-Compiler from samples\flexstore\ProductListEvent.as
 * samples.flexstore.ProductListEvent
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes}
 */

goog.provide('samples.flexstore.ProductListEvent');

goog.require('org.apache.flex.events.Event');



/**
 * @constructor
 * @extends {org.apache.flex.events.Event}
 * @param {string} type
 * @param {boolean=} bubbles
 * @param {boolean=} cancelable
 */
samples.flexstore.ProductListEvent = function(type, bubbles, cancelable) {
  bubbles = typeof bubbles !== 'undefined' ? bubbles : true;
  cancelable = typeof cancelable !== 'undefined' ? cancelable : false;
  samples.flexstore.ProductListEvent.base(this, 'constructor', type, bubbles, cancelable);
};
goog.inherits(samples.flexstore.ProductListEvent, org.apache.flex.events.Event);


/**
 * @export
 * @const
 * @type {string}
 */
samples.flexstore.ProductListEvent.ADD_PRODUCT = "addProduct";


/**
 * @export
 * @const
 * @type {string}
 */
samples.flexstore.ProductListEvent.DUPLICATE_PRODUCT = "duplicateProduct";


/**
 * @export
 * @const
 * @type {string}
 */
samples.flexstore.ProductListEvent.REMOVE_PRODUCT = "removeProduct";


/**
 * @export
 * @const
 * @type {string}
 */
samples.flexstore.ProductListEvent.PRODUCT_QTY_CHANGE = "productQtyChange";


/**
 * @export
 * @type {samples.flexstore.Product}
 */
samples.flexstore.ProductListEvent.prototype.product;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
samples.flexstore.ProductListEvent.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'ProductListEvent', qName: 'samples.flexstore.ProductListEvent'}] };
