/**
 * Generated by Apache Flex Cross-Compiler from org/apache/flex/states/Transition.as
 * org.apache.flex.states.Transition
 *
 * @fileoverview
 *
 * @suppress {checkTypes}
 */

goog.provide('org.apache.flex.states.Transition');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion FlexJS 0.0
 * @constructor
 */
org.apache.flex.states.Transition = function() {
  ;
};


/**
 * @export
 * @type {string}
 */
org.apache.flex.states.Transition.prototype.fromState;


/**
 * @export
 * @type {string}
 */
org.apache.flex.states.Transition.prototype.toState;


/**
 * @export
 * @type {Array}
 */
org.apache.flex.states.Transition.prototype.effects;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.flex.states.Transition.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Transition', qName: 'org.apache.flex.states.Transition'}] };
